services:
  h2-db:
    image: oscarfonts/h2
    container_name: h2-db
    ports:
      - "1521:1521"
      - "81:81"
    environment:
      - H2_OPTIONS=-tcp -tcpAllowOthers -ifNotExists
    networks:
      - kaddem-network
    restart: unless-stopped

  kaddem-app:
    image: 192.168.235.132:8082/docker-releases2/kaddem-backend:latest
    container_name: kaddem-app
    depends_on:
      - h2-db
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2-db:1521/mem:kaddem
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.H2Dialect
      SPRING_H2_CONSOLE_ENABLED: "true"
      SPRING_H2_CONSOLE_PATH: /h2-console
    networks:
      - kaddem-network
    restart: unless-stopped

  frontend-app:
    image: 192.168.235.132:8082/docker-releases2/react-frontend:latest
    container_name: frontend-app
    ports:
      - "5173:80"
    networks:
      - kaddem-network
    restart: unless-stopped
    depends_on:
      - kaddem-app

networks:
  kaddem-network:
    external: true
